name = "id1-xuts-telkom"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "updates.netflix.com.telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "www.udemy.com.telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "investor.spotify.com.telkom.vpnyubi.my.id"
custom_domain = true
[[routes]]
pattern = "ruangguru.com.telkom.vpnyubi.my.id"
custom_domain = true

[vars]
PROXYIP = "36.95.152.58:12137"
UUID = "01164cc6-598c-4a4a-b91d-c6e0e8d11545"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
